### ISSUE TITLE
/sample-page not found

### ISSUE THREAD

**Issue by JonathanMH** [northosts/wuxt#5]
When trying to access `http://0.0.0.0:3000/sample-page` the front.wuxt container responds with a 404 error.

Steps to reproduce:

1. clone the repository
2. docker-compose up
3. click the "sample page" link

This issue persists after completing the wordpress installation at `localhost:3080`

**Comment by northosts** [comment]
Hi thanks for reporting! Two questions: 

- is there a Sample Page in wp-admin->Pages? It should have been created by the WP-installation
- did you set permalinks to "Postname", otherwise the wp-json endpoint will not work.

If I follow your steps + WP installation + Permalinks to "Postname", I don't get a 404.

**Comment by JonathanMH** [comment]
Hi! Yes, there is a sample page and I have also checked changing the permalinks, however the output of docker-compose up (without `-d`) shows:

```
wp.wuxt       | 172.21.0.4 - - [13/May/2019:09:14:20 +0000] "GET /wp-json/wuxt/v1/slug/sample-page HTTP/1.1" 404 562 "-" "node-superagent/4.1.0"
```

Does that route resolve for you?

**Comment by northosts** [comment]
Yes it does, fresh install, installation steps as described above, with one addition: Did you activate the wuxt theme in WordPress? The theme activates the custom wuxt-endpoints, that might be the missing part.

`wp.wuxt       | 172.20.0.2 - - [13/May/2019:11:32:00 +0000] "GET /wp-json/wuxt/v1/slug/sample-page HTTP/1.1" 200 3646 "-" "node-superagent/4.1.0"`

Otherwise the problem might be Windows? I've tested on Ubuntu/Linux and Mac. Mac is running Docker inside an Linux virtual machine, that's why the Ip (would be in my case 172.20.0.2) is not resolving from the host. `http://localhost:3080/wp-json/wuxt/v1/slug/sample-page` is resolving, though.

Thanks for the input, it's very much appreciated!

**Comment by JonathanMH** [comment]
Oh, good point! I did not activate the theme! I'll try that again, my tests were done on Ubuntu 18.04

**Comment by northosts** [comment]
Nice, that should be it :)
I've made that more clear in the docs!

![image](https://user-images.githubusercontent.com/44435416/57620460-1b453300-7589-11e9-9066-ea7ae9d4e28a.png)
